name: CI/CD for dbt

on:
  push:
    branches:
      - ankur-patch-1
      - main
  pull_request:
    branches:
      - main

jobs:
  dbt-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dbt
        run: pip install dbt-core dbt-snowflake

      - name: Create profiles.yml
        run: |
          mkdir -p ~/.dbt
          echo "${{ secrets.DBT_PROFILES_YML }}" | base64 --decode > ~/.dbt/profiles.yml

      - name: Debug profiles.yml
        run: cat ~/.dbt/profiles.yml

      - name: Run dbt Debug
        run: dbt debug

      - name: Run dbt Tests
        run: dbt test
